### PR TITLE
Fix grid gap syntax in style.css

### PR DESCRIPTION
**Pull request by ElenaGen**
I spot an unfixed change. This needs to be fixed.

### CODE REVIEW

**Comment by ElenaGen** [comment]
I made a small fix, which was lost in the middle of merging chaos. Please accept.

**Comment by ElenaGen** [comment]
I noticed that the icon folder was added to .gitignore. Which probably prevented me from committing some necessary icons. The "star rating" was shown with the missing stars. 

I removed the icon folder from .gitignore and added the actual folder to the pull request.

**Review by Umka-dev — COMMENTED** [review]
Elena, I see the display of stars was fixed. It looks good.  

I have a question before merging: why do you duplicate logo_en.svg to the folder "icons" if it already exists in the "images" folder? At the same time, you didn't use a link to icons/logo_en.svg in your header HTML code but have a link to the "images" folder. I guess this file should be deleted.

**Review by Umka-dev — COMMENTED** [review]
Indeed, the gitignor file excluded a similar folder by default. This should have led to the idea that there is no need to create it, because we already have an images folder, and all the pictures, including icons, should be placed there.

But if you really want this folder to exist, then you can rename the "icon" folder to "icons" and put it in the images folder, and again adjust the links to these icons after moving.

I would ask you to delete logo_en.svg since it is no longer used anywhere. That logo link was broken in the first pull request, and I already fixed it.

**Review by Umka-dev — APPROVED** [review]
Its OK now.

**Pull request merged**
